package com.example.skolaback.model.enumerations;

public enum Profession {
    ADMINISTRATION,
    ECONOMICS_FINANCE_AND_INSURANCE,
    ELECTRICAL_ENGINEERING_AND_TELECOMMUNICATIONS,
    MEDICINE,
    ARCHITECTURE_CONSTRUCTION_AND_GEODESY,
    OTHER
}
